name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-snake.svg?palette=github-dark&color_dots=#333333,#555555,#777777,#999999,#BBBBBB
            output/github-snake-dark.svg?palette=github-dark&color_dots=#333333,#555555,#777777,#999999,#BBBBBB
            output/ocean.gif?palette=github-dark&color_snake=orange&color_dots=#333333,#555555,#777777,#999999,#BBBBBB
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
